#!/usr/bin/env python3

import os
import sys
import time
from generate_questions import generate_questions, add_questions_to_database


def generate_batch():
    """
    Generate a batch of questions across multiple categories and difficulties.
    """
    # categories = [
    #     "Technology",
    #     "Science",
    #     "Geography",
    #     "History",
    #     "Literature",
    #     "Sports",
    #     "Music",
    #     "Art",
    #     "Film",
    #     "Arsenal FC",
    #     "Liverpool FC",
    #     "Manchester United",
    #     "Fantasy Premier League",
    #     "Nobel",
    #     "Geography - Africa",
    #     "Geography - Europe",
    #     "Geography - South-America",
    #     "Geography - North-America",
    #     "Geography - Asia",
    #     "Geography - Rivers",
    #     "Geography - Mountains",
    #     "Movies",
    #     "Animals",
    #     "Space",
    #     "Economics",
    #     "Austrian Economics",
    #     "Economics - Austrian Economics",
    #     "Economics - Austrian Economics - Ludwig von Mises",
    #     "Economics - Austrian Economics - Friedrich Hayek",
    #     "Economics - Austrian Economics - Joseph Schumpeter",
    #     "Economics - Austrian Economics - Murray Rothbard",
    #     "Economics - Austrian Economics - Ludwig von Mises",
    #     "Sports - Football",
    #     "Sports - Basketball",
    #     "Sports - Tennis",
    #     "Sports - Formula 1",
    #     "Sports - Olympic Games",
    #     "Sports - English Premier League",
    #     "Sports - English Premier League Players",
    #     "Sports - English Premier League Teams",
    #     "Sports - English Premier League Players",
    #     "Art - Art History",
    #
    #
    # ]

    categories = [
        "Sports - Football",
        "Sports - Football - International Competitions",
        "Sports - Football - International Competitions - FIFA World Cup",
        "Sports - Football - International Competitions - FIFA Women's World Cup",
        "Sports - Football - International Competitions - UEFA European Championship (Euros)",
        "Sports - Football - International Competitions - Copa América",
        "Sports - Football - International Competitions - Africa Cup of Nations (AFCON)",
        "Sports - Football - International Competitions - AFC Asian Cup",
        "Sports - Football - International Competitions - UEFA Nations League",
        "Sports - Football - International Competitions - CONCACAF Gold Cup",
        "Sports - Football - Club Competitions",
        "Sports - Football - Club Competitions - UEFA Champions League",
        "Sports - Football - Club Competitions - UEFA Europa League",
        "Sports - Football - Club Competitions - UEFA Conference League",
        "Sports - Football - Club Competitions - UEFA Women's Champions League",
        "Sports - Football - Club Competitions - Copa Libertadores",
        "Sports - Football - Club Competitions - Copa Sudamericana",
        "Sports - Football - Club Competitions - FIFA Club World Cup",
        "Sports - Football - English Football",
        "Sports - Football - English Football - Premier League",
        "Sports - Football - English Football - Premier League - Arsenal FC",
        "Sports - Football - English Football - Premier League - Aston Villa",
        "Sports - Football - English Football - Premier League - Brighton & Hove Albion",
        "Sports - Football - English Football - Premier League - Chelsea FC",
        "Sports - Football - English Football - Premier League - Crystal Palace",
        "Sports - Football - English Football - Premier League - Everton",
        "Sports - Football - English Football - Premier League - Fulham",
        "Sports - Football - English Football - Premier League - Ipswich Town",
        "Sports - Football - English Football - Premier League - Leicester City",
        "Sports - Football - English Football - Premier League - Liverpool FC",
        "Sports - Football - English Football - Premier League - Manchester City",
        "Sports - Football - English Football - Premier League - Manchester United",
        "Sports - Football - English Football - Premier League - Newcastle United",
        "Sports - Football - English Football - Premier League - Nottingham Forest",
        "Sports - Football - English Football - Premier League - Southampton",
        "Sports - Football - English Football - Premier League - Tottenham Hotspur",
        "Sports - Football - English Football - Premier League - West Ham United",
        "Sports - Football - English Football - Premier League - Wolverhampton Wanderers",
        "Sports - Football - English Football - Championship",
        "Sports - Football - English Football - FA Cup",
        "Sports - Football - English Football - League Cup (Carabao Cup)",
        "Sports - Football - Fantasy Premier League",
        "Sports - Football - Spanish Football",
        "Sports - Football - Spanish Football - La Liga",
        "Sports - Football - Spanish Football - La Liga - Athletic Bilbao",
        "Sports - Football - Spanish Football - La Liga - Atlético Madrid",
        "Sports - Football - Spanish Football - La Liga - FC Barcelona",
        "Sports - Football - Spanish Football - La Liga - Real Betis",
        "Sports - Football - Spanish Football - La Liga - Real Madrid",
        "Sports - Football - Spanish Football - La Liga - Real Sociedad",
        "Sports - Football - Spanish Football - La Liga - Sevilla FC",
        "Sports - Football - Spanish Football - La Liga - Valencia CF",
        "Sports - Football - Spanish Football - La Liga - Villarreal CF",
        "Sports - Football - Spanish Football - Copa del Rey",
        "Sports - Football - German Football",
        "Sports - Football - German Football - Bundesliga",
        "Sports - Football - German Football - Bundesliga - Bayer 04 Leverkusen",
        "Sports - Football - German Football - Bundesliga - Bayern Munich",
        "Sports - Football - German Football - Bundesliga - Borussia Dortmund",
        "Sports - Football - German Football - Bundesliga - Borussia Mönchengladbach",
        "Sports - Football - German Football - Bundesliga - Eintracht Frankfurt",
        "Sports - Football - German Football - Bundesliga - RB Leipzig",
        "Sports - Football - German Football - DFB-Pokal",
        "Sports - Football - Italian Football",
        "Sports - Football - Italian Football - Serie A",
        "Sports - Football - Italian Football - Serie A - AC Milan",
        "Sports - Football - Italian Football - Serie A - AS Roma",
        "Sports - Football - Italian Football - Serie A - Atalanta",
        "Sports - Football - Italian Football - Serie A - Fiorentina",
        "Sports - Football - Italian Football - Serie A - Inter Milan",
        "Sports - Football - Italian Football - Serie A - Juventus",
        "Sports - Football - Italian Football - Serie A - Lazio",
        "Sports - Football - Italian Football - Serie A - Napoli",
        "Sports - Football - Italian Football - Coppa Italia",
        "Sports - Football - French Football",
        "Sports - Football - French Football - Ligue 1",
        "Sports - Football - French Football - Ligue 1 - AS Monaco",
        "Sports - Football - French Football - Ligue 1 - Lille OSC",
        "Sports - Football - French Football - Ligue 1 - Olympique Lyonnais",
        "Sports - Football - French Football - Ligue 1 - Olympique de Marseille",
        "Sports - Football - French Football - Ligue 1 - Paris Saint-Germain",
        "Sports - Football - Other European Leagues",
        "Sports - Football - Other European Leagues - Eredivisie (Netherlands)",
        "Sports - Football - Other European Leagues - Eredivisie - AFC Ajax",
        "Sports - Football - Other European Leagues - Eredivisie - Feyenoord",
        "Sports - Football - Other European Leagues - Eredivisie - PSV Eindhoven",
        "Sports - Football - Other European Leagues - Primeira Liga (Portugal)",
        "Sports - Football - Other European Leagues - Primeira Liga - SL Benfica",
        "Sports - Football - Other European Leagues - Primeira Liga - FC Porto",
        "Sports - Football - Other European Leagues - Primeira Liga - Sporting CP",
        "Sports - Football - Other European Leagues - Scottish Premiership",
        "Sports - Football - Other European Leagues - Scottish Premiership - Celtic FC",
        "Sports - Football - Other European Leagues - Scottish Premiership - Rangers FC",
        "Sports - Football - Other European Leagues - Süper Lig (Turkey)",
        "Sports - Football - Players",
        "Sports - Football - Players - Legends",
        "Sports - Football - Players - Legends - Pelé",
        "Sports - Football - Players - Legends - Diego Maradona",
        "Sports - Football - Players - Legends - Johan Cruyff",
        "Sports - Football - Players - Legends - Franz Beckenbauer",
        "Sports - Football - Players - Current Stars",
        "Sports - Football - Players - Current Stars - Lionel Messi",
        "Sports - Football - Players - Current Stars - Cristiano Ronaldo",
        "Sports - Football - Players - Current Stars - Kylian Mbappé",
        "Sports - Football - Players - Current Stars - Erling Haaland",
        "Sports - Football - Awards",
        "Sports - Football - Awards - Ballon d'Or",
        "Sports - Tennis",
        "Sports - Tennis - Grand Slams",
        "Sports - Tennis - Grand Slams - Australian Open",
        "Sports - Tennis - Grand Slams - French Open (Roland Garros)",
        "Sports - Tennis - Grand Slams - Wimbledon",
        "Sports - Tennis - Grand Slams - US Open",
        "Sports - Tennis - Tours",
        "Sports - Tennis - Tours - ATP Tour",
        "Sports - Tennis - Tours - WTA Tour",
        "Sports - Tennis - Tournaments",
        "Sports - Tennis - Tournaments - ATP Finals",
        "Sports - Tennis - Tournaments - WTA Finals",
        "Sports - Tennis - Tournaments - Masters 1000",
        "Sports - Tennis - Team Competitions",
        "Sports - Tennis - Team Competitions - Davis Cup",
        "Sports - Tennis - Team Competitions - Billie Jean King Cup",
        "Sports - Tennis - Team Competitions - Laver Cup",
        "Sports - Tennis - Players",
        "Sports - Tennis - Players - Male Legends",
        "Sports - Tennis - Players - Male Legends - Roger Federer",
        "Sports - Tennis - Players - Male Legends - Rafael Nadal",
        "Sports - Tennis - Players - Male Legends - Novak Djokovic",
        "Sports - Tennis - Players - Male Legends - Björn Borg",
        "Sports - Tennis - Players - Female Legends",
        "Sports - Tennis - Players - Female Legends - Serena Williams",
        "Sports - Tennis - Players - Female Legends - Steffi Graf",
        "Sports - Tennis - Players - Female Legends - Martina Navratilova",
        "Sports - Formula 1",
        "Sports - Formula 1 - Teams",
        "Sports - Formula 1 - Teams - Scuderia Ferrari",
        "Sports - Formula 1 - Teams - Mercedes-AMG Petronas F1 Team",
        "Sports - Formula 1 - Teams - Red Bull Racing",
        "Sports - Formula 1 - Teams - McLaren F1 Team",
        "Sports - Formula 1 - Teams - Alpine F1 Team",
        "Sports - Formula 1 - Teams - Aston Martin F1 Team",
        "Sports - Formula 1 - Teams - Williams Racing",
        "Sports - Formula 1 - Drivers",
        "Sports - Formula 1 - Drivers - Lewis Hamilton",
        "Sports - Formula 1 - Drivers - Max Verstappen",
        "Sports - Formula 1 - Drivers - Charles Leclerc",
        "Sports - Formula 1 - Drivers - Lando Norris",
        "Sports - Formula 1 - Drivers - Legends",
        "Sports - Formula 1 - Drivers - Legends - Ayrton Senna",
        "Sports - Formula 1 - Drivers - Legends - Michael Schumacher",
        "Sports - Formula 1 - Drivers - Legends - Alain Prost",
        "Sports - Formula 1 - Circuits",
        "Sports - Formula 1 - Circuits - Monaco Grand Prix",
        "Sports - Formula 1 - Circuits - Silverstone Circuit",
        "Sports - Formula 1 - Circuits - Monza Circuit",
        "Sports - Formula 1 - Circuits - Spa-Francorchamps",
        "Sports - Ice Hockey",
        "Sports - Ice Hockey - NHL",
        "Sports - Ice Hockey - NHL - Eastern Conference",
        "Sports - Ice Hockey - NHL - Eastern Conference - Boston Bruins",
        "Sports - Ice Hockey - NHL - Eastern Conference - Toronto Maple Leafs",
        "Sports - Ice Hockey - NHL - Eastern Conference - New York Rangers",
        "Sports - Ice Hockey - NHL - Western Conference",
        "Sports - Ice Hockey - NHL - Western Conference - Edmonton Oilers",
        "Sports - Ice Hockey - NHL - Western Conference - Colorado Avalanche",
        "Sports - Ice Hockey - NHL - Stanley Cup",
        "Sports - Ice Hockey - European Leagues",
        "Sports - Ice Hockey - European Leagues - KHL (Kontinental Hockey League)",
        "Sports - Ice Hockey - European Leagues - SHL (Swedish Hockey League)",
        "Sports - Ice Hockey - European Leagues - Liiga (Finland)",
        "Sports - Ice Hockey - European Leagues - DEL (Germany)",
        "Sports - Ice Hockey - International",
        "Sports - Ice Hockey - International - IIHF World Championship",
        "Sports - Ice Hockey - International - Olympic Ice Hockey",
        "Sports - Ice Hockey - Players",
        "Sports - Ice Hockey - Players - Wayne Gretzky",
        "Sports - Ice Hockey - Players - Sidney Crosby",
        "Sports - Ice Hockey - Players - Connor McDavid",
        "Sports - UFC (Mixed Martial Arts)",
        "Sports - UFC - Heavyweight",
        "Sports - UFC - Light Heavyweight",
        "Sports - UFC - Middleweight",
        "Sports - UFC - Welterweight",
        "Sports - UFC - Lightweight",
        "Sports - UFC - Featherweight",
        "Sports - UFC - Bantamweight",
        "Sports - UFC - Women's Divisions",
        "Sports - UFC - Fighters",
        "Sports - UFC - Fighters - Jon Jones",
        "Sports - UFC - Fighters - Conor McGregor",
        "Sports - UFC - Fighters - Khabib Nurmagomedov",
        "Sports - UFC - Fighters - Islam Makhachev",
        "Sports - Basketball",
        "Sports - Basketball - NBA",
        "Sports - Basketball - NBA - Boston Celtics",
        "Sports - Basketball - NBA - Los Angeles Lakers",
        "Sports - Basketball - NBA - Golden State Warriors",
        "Sports - Basketball - NBA - Chicago Bulls",
        "Sports - Basketball - European Basketball",
        "Sports - Basketball - European Basketball - EuroLeague",
        "Sports - Basketball - European Basketball - EuroLeague - Real Madrid Baloncesto",
        "Sports - Basketball - European Basketball - EuroLeague - FC Barcelona Bàsquet",
        "Sports - Basketball - European Basketball - EuroLeague - Panathinaikos BC",
        "Sports - Basketball - International",
        "Sports - Basketball - International - FIBA Basketball World Cup",
        "Sports - Cycling",
        "Sports - Cycling - Grand Tours",
        "Sports - Cycling - Grand Tours - Tour de France",
        "Sports - Cycling - Grand Tours - Giro d'Italia",
        "Sports - Cycling - Grand Tours - Vuelta a España",
        "Sports - Cycling - Monuments",
        "Sports - Cycling - Monuments - Milan-San Remo",
        "Sports - Cycling - Monuments - Tour of Flanders",
        "Sports - Cycling - Monuments - Paris-Roubaix",
        "Sports - Cycling - Monuments - Liège-Bastogne-Liège",
        "Sports - Cycling - Monuments - Il Lombardia",
        "Sports - Rugby Union",
        "Sports - Rugby Union - International",
        "Sports - Rugby Union - International - Rugby World Cup",
        "Sports - Rugby Union - International - Six Nations Championship",
        "Sports - Rugby Union - International - The Rugby Championship",
        "Sports - Rugby Union - Clubs",
        "Sports - Rugby Union - Clubs - European Rugby Champions Cup",
        "Sports - Rugby Union - Clubs - English Premiership",
        "Sports - Rugby Union - Clubs - Top 14 (France)",
        "Sports - Golf",
        "Sports - Golf - Majors",
        "Sports - Golf - Majors - The Masters Tournament",
        "Sports - Golf - Majors - PGA Championship",
        "Sports - Golf - Majors - U.S. Open",
        "Sports - Golf - Majors - The Open Championship",
        "Sports - Golf - Team Competitions",
        "Sports - Golf - Team Competitions - Ryder Cup",
        "Sports - Athletics",
        "Sports - Athletics - World Athletics Championships",
        "Sports - Athletics - Diamond League",
        "Sports - Athletics - Disciplines",
        "Sports - Athletics - Disciplines - Sprints",
        "Sports - Athletics - Disciplines - Middle and Long Distance",
        "Sports - Athletics - Disciplines - Field Events",
        "Sports - Other Motorsports",
        "Sports - Other Motorsports - MotoGP",
        "Sports - Other Motorsports - World Rally Championship (WRC)",
        "Sports - Other Motorsports - 24 Hours of Le Mans",
        "Sports - Handball",
        "Sports - Handball - EHF Champions League",
        "Sports - Handball - World Men's Handball Championship",
        "Sports - Winter Sports",
        "Sports - Winter Sports - Alpine Skiing World Cup",
        "Sports - Winter Sports - Biathlon World Cup",
        "Sports - Winter Sports - Ski Jumping",
        "Sports - Olympic Games",
        "Sports - Olympic Games - Summer Olympics",
        "Sports - Olympic Games - Winter Olympics",
        "E-Sports - General",
        "E-Sports by Game",
        "E-Sports - League of Legends (LoL)",
        "E-Sports - League of Legends - World Championship (Worlds)",
        "E-Sports - League of Legends - LEC (League of Legends EMEA Championship)",
        "E-Sports - Counter-Strike 2 (CS2)",
        "E-Sports - Counter-Strike 2 - Majors",
        "E-Sports - Dota 2",
        "E-Sports - Dota 2 - The International",
        "E-Sports - Valorant",
        "E-Sports - Valorant - Champions Tour (VCT)",
        "E-Sports - Fortnite",
        "E-Sports - Call of Duty League (CDL)",
        "E-Sports - Rocket League Championship Series (RLCS)",
        "E-Sports - Fighting Games",
        "E-Sports - Fighting Games - Evolution Championship Series (EVO)",
        "E-Sports - Teams",
        "E-Sports - Players & Personalities",
        "Video Games - General",
        "Video Games by Genre",
        "Video Games - Role-Playing Games (RPGs)",
        "Video Games - RPGs - The Witcher Series",
        "Video Games - RPGs - Elden Ring",
        "Video Games - Action-Adventure",
        "Video Games - Action-Adventure - Grand Theft Auto (GTA)",
        "Video Games - Action-Adventure - Assassin's Creed",
        "Video Games - First-Person Shooters (FPS)",
        "Video Games - FPS - Call of Duty Series",
        "Video Games - FPS - Battlefield Series",
        "Video Games - Strategy Games",
        "Video Games - Strategy Games - Civilization Series",
        "Video Games - Strategy Games - Total War Series",
        "Video Games - Simulation Games",
        "Video Games - Sports Games",
        "Video Games - Sports Games - EA Sports FC",
        "Video Games - Sports Games - NBA 2K",
        "Video Games by Platform",
        "Video Games - PC Gaming",
        "Video Games - Console Gaming",
        "Video Games - Indie Games",
        "Video Games - Retro Gaming",
        "Traditional Games - General",
        "Board Games",
        "Board Games - Strategy",
        "Board Games - Party Games",
        "Card Games",
        "Card Games - Traditional",
        "Card Games - Collectible Card Games",
        "Tabletop Role-Playing Games (TTRPGs)",
        "Tabletop RPGs - Dungeons & Dragons (D&D)",
        "Gambling - General",
        "Sports Betting",
        "Sports Betting - Football Betting",
        "Sports Betting - Horse Racing",
        "Sports Betting - Strategy & Odds",
        "Casino Games",
        "Casino Games - Poker",
        "Casino Games - Poker - Texas Hold'em",
        "Casino Games - Poker - World Series of Poker (WSOP)",
        "Casino Games - Blackjack",
        "Casino Games - Roulette",
    ]
    # difficulties = ["Easy", "Medium", "Hard"]
    difficulties = ["Hard"]

    # Check for API key
    if not os.environ.get("GEMINI_API_KEY"):
        print("Please set the GEMINI_API_KEY environment variable")
        sys.exit(1)

    questions_per_batch = 3  # Questions per category/difficulty combination
    total_questions = 0

    print(
        f"Generating {questions_per_batch} questions for each category/difficulty combination..."
    )
    print(
        f"Total: {len(categories)} categories × {len(difficulties)} difficulties × {questions_per_batch} questions = {len(categories) * len(difficulties) * questions_per_batch} questions"
    )

    for category in categories:
        for difficulty in difficulties:
            print(
                f"\nGenerating {questions_per_batch} {difficulty} questions for {category}..."
            )

            try:
                # Generate questions
                questions_data = generate_questions(
                    category, difficulty, questions_per_batch
                )

                if questions_data:
                    # Add to database
                    added_count = add_questions_to_database(questions_data)
                    total_questions += added_count
                    print(f"✓ Added {added_count} questions")
                else:
                    print(
                        f"✗ Failed to generate questions for {category} ({difficulty})"
                    )

                # Small delay to avoid rate limiting
                time.sleep(1)

            except Exception as e:
                print(f"✗ Error processing {category} ({difficulty}): {e}")
                continue

    print(f"\n🎉 Batch generation complete! Total questions added: {total_questions}")


if __name__ == "__main__":
    generate_batch()
